version: "3"
services:
  php:
    build: .docker/php
    container_name: "php-srv"
    image: server-php-nginx
    volumes:
      - .:/var/www/html
    ports:
      - "9000:9000"
    restart: always
    networks:
      - mynetwork

  nginx:
    image: nginx
    container_name: "nginx-srv"
    volumes:
      - .docker/nginx/server.pem:/etc/nginx/ssl/server.pem
      - .docker/nginx/server-key.pem:/etc/nginx/ssl/server-key.pem
      - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
    ports:
      - "80:80"
      - "443:443"
    restart: always
    networks:
      - mynetwork

  postgres:
    image: postgres:latest
    container_name: "postgres-srv"
    ports:
      - "5432:5432"
    volumes:
      - .docker/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "docker"
    restart: always
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
